const NAVIGATION_PREFIX = 'TO_NGUYEN_';
export const ROOT = `${NAVIGATION_PREFIX}Root`;
const APP_SCREEN = `${NAVIGATION_PREFIX}APP_SCREEN`;
const ALERT_POPUP = `${NAVIGATION_PREFIX}ALERT_POPUP`;
const LOADING_SCREEN = `${NAVIGATION_PREFIX}LOADING_SCREEN`;
const HOME_SCREEN = `${NAVIGATION_PREFIX}HOME_SCREEN`;
const SETTING_SCREEN = `${NAVIGATION_PREFIX}SETTING_SCREEN`;
const LOGIN_SCREEN = `${NAVIGATION_PREFIX}LOGIN_SCREEN`;

export {
  APP_SCREEN,
  ALERT_POPUP,
  LOADING_SCREEN,
  HOME_SCREEN,
  LOGIN_SCREEN,
  SETTING_SCREEN,
};
